Algoritmo "LacoEnquanto"
// Disciplina   : [Lógica de Programação]
// Professor   :Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius Mendes da Silva
// Data atual  : 09/09/2024
Var
   // Seção de Declarações das variáveis
   contadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto contadora<10 faca
      Escreval("Vinicius")
      contadora<-contadora+1
   fimenquanto


Fimalgoritmo